#Khinenw's ToAruShop
name: ToAruShop
author: Khinenw
version: "0.0.1 alpha"
description: "An Shop for ToAruPG"
main: Khinenw\AruPG\ToAruShop
api: 1.12.0
depend: [EconomyAPI, TAPGAPI]

permissions:
  arushop.*:
    description: "The permission for using features of To Aru Shop."
    default: true
    children:
      arushop.buy.*:
        default: true
        description: "The permission for buying."
        children:
          arushop.buy.job:
            default:true
            description: "The permission for buying jobs."

          arushop.buy.set:
            default:true
            description: "The permission for buying sets (job + skills)."

          arushop.buy.skill:
            default:true
            description: "The permission for buying skills."

      arushop.create:
        default: op
        description: "The permission for creating shopss."
      
      arushop.destroy:
        default: op
        description: "The permission for destroying shops."